[workspace]
authors = ["canoe <liwentao0705@outlook.com>"]
channels = ["conda-forge", "nvidia"]
name = "mmrotate-detr"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
install-mmcv = { cmd = "uv pip install git+https://git.airvic.top/canoe/mmcv.git@main --no-build-isolation" }
setup = { cmd = "uv pip install -e . --config-settings editable-mode=compat --no-build-isolation", depends-on = [
    "install-mmcv",
] }

[dependencies]
python = "3.13.*"
cuda-toolkit = "12.9.*"
numpy = ">=1.19.0"
opencv = ">=4.12.0,<5"
pillow = ">=11.3.0,<12"
matplotlib = ">=3.10.3,<4"
scipy = ">=1.16.0,<2"
tqdm = ">=4.67.1,<5"
tensorboard = ">=2.20.0,<3"
wandb = ">=0.21.0,<0.22"
uv = ">=0.8.3,<0.9"
ninja = ">=1.13.1,<2"
icecream = ">=2.1.5,<3"
pip = ">=25.2,<26"

[pypi-dependencies]
torch = { version = ">=2.8.0", index = "https://download.pytorch.org/whl/cu129" }
torchvision = { version = ">=0.23.0", index = "https://download.pytorch.org/whl/cu129" }
mmengine = ">=0.8.0"
timm = ">=1.0.0"
